#!/bin/sh
 
 
blkdev=`dirname $DEVPATH`
if [ `basename $blkdev` != "block" ]; then
 
    device=`basename $DEVPATH`
    if [ "${device:0:2}" = "sd" ];then
		case "$ACTION" in
			add)
				mkdir -p /mnt/$device
				sleep 0.5
	            nowtime=`cat /proc/uptime | awk -F "." '{print $1}'`
	            limit_time=15
	            if [ $nowtime -lt $limit_time  ];then
	                    dtime=`expr $limit_time - $nowtime`
	                    sleep $dtime
	            fi

	       	 	# vfat & ntfs-3g check
	        	if  [ `which fdisk` ]; then
	                	isntfs=`fdisk -l | grep $device | grep NTFS`
	                	isvfat=`fdisk -l | grep $device | grep FAT`
	                	isfuse=`lsmod | grep fuse`
	                	isntfs3g=`which ntfs-3g`
	        	else
	                	isntfs=""
	                	isvfat=""
	        	fi 
				num=0	
				while [ $num -lt 3 ]
				do 
	        		# mount with ntfs-3g if possible, else with default mount
	        		if [ "$isntfs" -a "$isfuse" -a "$isntfs3g" ]; then
	                		ntfs-3g -o nls=utf8 /dev/$device /mnt/$device
	        		elif [ "$isvfat" ]; then
	                		mount -t vfat -o iocharset=utf8,rw,sync,umask=0000,dmask=0000,fmask=0000 /dev/$device /mnt/$device
	        		else
	                		mount /dev/$device /mnt/$device
	        		fi
					if [ $? -eq 0 ];then
						break
					fi
					sleep 2
					num=`expr $num + 1`
				done
	            ;;

			remove)
	        	umount /dev/$device
	        	;;
		esac
    fi
fi
